/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinterface;

/**
 *
 * @author chint
 */
public class rpgui extends javax.swing.JFrame implements clientinterface.ClientInterface{
    int port;
    usercommandhandler.UserCommandHandler myUserCommandHandler;
    /**
     * Creates new form rpgui
     */
    public rpgui() {
        initComponents();
        port=9761;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        buttonToggleLed1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        buttonToggleConnectServer = new javax.swing.JToggleButton();
        buttonToggleLed2 = new javax.swing.JToggleButton();
        buttonToggleLed3 = new javax.swing.JToggleButton();
        buttonToggleLed4 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaServerMessges = new javax.swing.JTextArea();
        buttonPushButton1State = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        buttonPushButton2State = new javax.swing.JButton();
        buttonPushButton3State = new javax.swing.JButton();
        buttonUpdatePort = new javax.swing.JButton();
        textFieldPortNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonToggleLed1.setSelected(true);
        buttonToggleLed1.setText("LED 1");
        buttonToggleLed1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonToggleLed1ActionPerformed(evt);
            }
        });
        buttonToggleLed1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonToggleLed1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buttonToggleLed1KeyReleased(evt);
            }
        });

        jLabel1.setText("LED Controls");

        buttonToggleConnectServer.setSelected(true);
        buttonToggleConnectServer.setText("Connect");
        buttonToggleConnectServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonToggleConnectServerActionPerformed(evt);
            }
        });

        buttonToggleLed2.setSelected(true);
        buttonToggleLed2.setText("LED 2");
        buttonToggleLed2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonToggleLed2ActionPerformed(evt);
            }
        });

        buttonToggleLed3.setSelected(true);
        buttonToggleLed3.setText("LED 3");
        buttonToggleLed3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonToggleLed3ActionPerformed(evt);
            }
        });

        buttonToggleLed4.setSelected(true);
        buttonToggleLed4.setText("LED 4");
        buttonToggleLed4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonToggleLed4ActionPerformed(evt);
            }
        });

        textAreaServerMessges.setColumns(20);
        textAreaServerMessges.setRows(5);
        textAreaServerMessges.setText("Server Messeges:\n");
        jScrollPane1.setViewportView(textAreaServerMessges);

        buttonPushButton1State.setText("Button 1");
        buttonPushButton1State.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPushButton1StateActionPerformed(evt);
            }
        });

        jLabel2.setText("Push Button Status");

        buttonPushButton2State.setText("Button 2");
        buttonPushButton2State.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPushButton2StateActionPerformed(evt);
            }
        });

        buttonPushButton3State.setText("Button 3");
        buttonPushButton3State.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPushButton3StateActionPerformed(evt);
            }
        });

        buttonUpdatePort.setText("Update Port");
        buttonUpdatePort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdatePortActionPerformed(evt);
            }
        });

        textFieldPortNumber.setText("9761");

        jLabel3.setText("Connection Controls ");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonToggleLed4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonToggleLed3)
                                        .addGap(18, 18, 18)
                                        .addComponent(buttonPushButton3State))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonToggleLed1)
                                        .addGap(18, 18, 18)
                                        .addComponent(buttonPushButton1State))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonToggleLed2)
                                        .addGap(18, 18, 18)
                                        .addComponent(buttonPushButton2State))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonToggleConnectServer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonUpdatePort)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textFieldPortNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonToggleConnectServer)
                    .addComponent(buttonUpdatePort)
                    .addComponent(textFieldPortNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buttonToggleLed1)
                                    .addComponent(buttonPushButton1State))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buttonPushButton2State)
                                    .addComponent(buttonToggleLed2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buttonToggleLed3)
                                    .addComponent(buttonPushButton3State))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonToggleLed4))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void update(String message){
        textAreaServerMessges.append("\n"+message);
    }
    
    public void setCommandHandler(usercommandhandler.UserCommandHandler commandHandler){
        this.myUserCommandHandler = commandHandler;
    }
    private void buttonToggleLed2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonToggleLed2ActionPerformed
        myUserCommandHandler.toggleLed(2);
    }//GEN-LAST:event_buttonToggleLed2ActionPerformed

    private void buttonUpdatePortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdatePortActionPerformed
        // TODO add your handling code here:
        port = Integer.parseInt(textFieldPortNumber.getText());
        textAreaServerMessges.append("\nPort number set to:"+port);
    }//GEN-LAST:event_buttonUpdatePortActionPerformed

    private void buttonToggleLed1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonToggleLed1ActionPerformed
        // TODO add your handling code here:
        myUserCommandHandler.toggleLed(1);
    }//GEN-LAST:event_buttonToggleLed1ActionPerformed

    private void buttonToggleLed1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonToggleLed1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonToggleLed1KeyPressed

    private void buttonToggleLed1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonToggleLed1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonToggleLed1KeyReleased

    private void buttonToggleConnectServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonToggleConnectServerActionPerformed
        // TODO add your handling code here:
        myUserCommandHandler.connectServer(port);
    }//GEN-LAST:event_buttonToggleConnectServerActionPerformed

    private void buttonToggleLed4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonToggleLed4ActionPerformed
        // TODO add your handling code here:
        myUserCommandHandler.toggleLed(4);
    }//GEN-LAST:event_buttonToggleLed4ActionPerformed

    private void buttonToggleLed3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonToggleLed3ActionPerformed
        // TODO add your handling code here:
        myUserCommandHandler.toggleLed(3);
    }//GEN-LAST:event_buttonToggleLed3ActionPerformed

    private void buttonPushButton1StateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPushButton1StateActionPerformed
        // TODO add your handling code here:
        myUserCommandHandler.getPushButton(1);
    }//GEN-LAST:event_buttonPushButton1StateActionPerformed

    private void buttonPushButton2StateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPushButton2StateActionPerformed
        // TODO add your handling code here:
        myUserCommandHandler.getPushButton(2);
    }//GEN-LAST:event_buttonPushButton2StateActionPerformed

    private void buttonPushButton3StateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPushButton3StateActionPerformed
        // TODO add your handling code here:
        myUserCommandHandler.getPushButton(3);
    }//GEN-LAST:event_buttonPushButton3StateActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(rpgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(rpgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(rpgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(rpgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new rpgui().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPushButton1State;
    private javax.swing.JButton buttonPushButton2State;
    private javax.swing.JButton buttonPushButton3State;
    private javax.swing.JToggleButton buttonToggleConnectServer;
    private javax.swing.JToggleButton buttonToggleLed1;
    private javax.swing.JToggleButton buttonToggleLed2;
    private javax.swing.JToggleButton buttonToggleLed3;
    private javax.swing.JToggleButton buttonToggleLed4;
    private javax.swing.JButton buttonUpdatePort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaServerMessges;
    private javax.swing.JTextField textFieldPortNumber;
    // End of variables declaration//GEN-END:variables
}
